apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: '{{ .Values.postgresql.postgresqlPassword | b64enc }}'
