apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
type: Opaque
data:
  password: '{{ .Values.postgresql.postgresqlPassword | b64enc }}'
